### ISSUE TITLE
turned based fighting example

### ISSUE THREAD

**Issue by shadow00dev** [GDevelopApp/GDevelop-examples#121]
## Describe the example
this is a turned based fighting example game with 1 player and enemy with 2 ability(fireball and summon zombie) also i made the art myself

heres a link to play it: https://shadow001.itch.io/turned-based-fighting-example
## Checklist

- [x] My game has all events unfolded.
- [x] My game has a proper name in the game properties. 
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] My game package name behind with `com.example.`.
- [x] I've cleaned unused resources.
- [x] Resources
- [x] Game properties
- [x] Objects
- [x] UI/scene layout
- [x] [FSM](http://wiki.compilgames.net/doku.php/gdevelop5/tutorials/finite_state_machine#how_to_handle_complex_logic_the_finite_state_machine_fsm)
- [x] Unused events
- [x] Factorize events

(the project folder is in comments)

**Comment by D8H** [comment]
Thank you for sharing this example.
I only took a quick look at the events. It seems that a FSM could make the events a lot clearer. This tutorial might help you:
http://wiki.compilgames.net/doku.php/gdevelop5/tutorials/finite_state_machine

Can you explain what concepts this example will bring to light?
I guess you wanted to show something like the FSM, but I only took a quick glance.

**Comment by shadow00dev** [comment]
> Thank you for sharing this example. I only took a quick look at the events. It seems that a FSM could make the events a lot clearer. This tutorial might help you: http://wiki.compilgames.net/doku.php/gdevelop5/tutorials/finite_state_machine
> 
> Can you explain what concepts this example will bring to light? I guess you wanted to show something like the FSM, but I only took a quick glance.

theres 1 animation for player 1 for enemy and 1 for zombie i would of assume i wouldn't need a FSM also i made this because someone asked for help on gdevelop discord a turned based game, and i realized gdevelop don't have a example so i made a example for gdevelop

**Comment by D8H** [comment]
> theres 1 animation for player 1 for enemy and 1 for zombie i would of assume i wouldn't need a FSM
The tutorial takes platformer animations as an example, FSM can be used for everything that need states. In the case of this example it could be:
* Wait user action
* Play player attack animation
* Play opponent attack animation
* Game over
It avoids to have the same condition repeated everywhere and make it clear what happens in each state.

But, maybe wait to have someone else opinion before doing changes because even though it could be a good template, I don't think it has its place as an example.

**Comment by Bouh** [comment]
My first opinion when I saw the game is how to play it?

There are texts on the screen, but I don't understand directly what I can do.
It's a problem with graphics and layout, you might be using the graphic assets from the asset store to make a more attractive game with a consistent style.

An FSM is welcome yes.
It allows having whole logic in groups, and better readability of the event sheet when logic is separate.

**Comment by Bouh** [comment]
What I spotted:
- Objects aren't all in PascalCase
- Variables name format is fancy, by convention prefer using PascalCase. e.g: Aility_use -> AilityUse  (is there a typo? It should be Agility?)
- I can see an empty parameter in the event sheet, even if this value is optional we fill every field, otherwise, an error appears in red. For an example we can not afford it, they must be almost perfect ;), 
- Not sure this format can be accepted on PlayStore `com.example.turned_based_fighting`

Art folder is great, nice to see this, it's a must to have, same for the readme :) !

**Comment by shadow00dev** [comment]
okay ill try and fix all these

**Comment by shadow00dev** [comment]
> It's a problem with graphics and layout, you might be using the graphic assets from the asset store to make a more attractive game with a consistent style.
> I understand this I just made my own art because I don't like using another people art(I know I'm not the best are making art) if I must 95% have to change it to some on the asset store I will, also I think its the grass that makes it inconsistent right, maybe I should try and do a alien grass thing instead(cuz the player and enemy don't look human)?

**Comment by shadow00dev** [comment]
> > theres 1 animation for player 1 for enemy and 1 for zombie i would of assume i wouldn't need a FSM
> 
> The tutorial takes platformer animations as an example, FSM can be used for everything that need states. In the case of this example it could be:
> 
> * Wait user action
> * Play player attack animation
> * Play opponent attack animation
> * Game over
> 
> It avoids to have the same condition repeated everywhere and make it clear what happens in each state.
> 
> But, maybe wait to have someone else opinion before doing changes because even though it could be a good template, I don't think it has its place as an example.

well i know I cant say this but I personally think this could help people with basics of some stuff In gdevelop and if anyone ever need help with making a turned based fighting system my example could help(it helped the person it was originally made for)

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7255117/TurnedBasedFighting.zip)
the only changes I haven't done is FSM and didn't use the asset store but I did change the art a little(hard to notice player and enemy changes in game but zombie change you will notice)

**Comment by D8H** [comment]
> > But, maybe wait to have someone else opinion before doing changes because even though it could be a good template, I don't think it has its place as an example.
> 
> well i know I cant say this but I personally think this could help people with basics of some stuff In gdevelop and if anyone ever need help with making a turned based fighting system my example could help(it helped the person it was originally made for)

It's totally alright. I just didn't want to make you work on it without the validation of someone that is more used to review examples (like Bouh).

**Comment by shadow00dev** [comment]
> > > But, maybe wait to have someone else opinion before doing changes because even though it could be a good template, I don't think it has its place as an example.
> > 
> > 
> > well i know I cant say this but I personally think this could help people with basics of some stuff In gdevelop and if anyone ever need help with making a turned based fighting system my example could help(it helped the person it was originally made for)
> 
> It's totally alright. I just didn't want to make you work on it without the validation of someone that is more used to review examples (like Bouh).

i would of probably done it anyway(for  the itch.io page to make it better) but okay, also this is the first time for this and I haven't done game dev in about a year and then i see that someone needed help i made a "crappy" example for him then made this one cuz i wanted to make it better so this is it i guess

**Comment by Bouh** [comment]
The idea of a Start scene is interesting.
I was thinking about a redesign of the presentation to make the project more attractive.
I strongly suggest using objects/textures from the asset store because there are icons and buttons.
It gives a style and a certain cachet to the example.
If you want my personal opinion, it is not presentable. That's why I'm pushing to have a minimum interface with sprites from the asset store.

I'm probably annoying, but the quality is essential. An example should be representative of the software and the games that are possible.

I see that you have indeed made some changes, continue the changes, it's on the right track!
- I see that there is at least one object not used, it has a default name.
- Click to start, is not centred.
- Use groups in the events, it makes the project much more structured.
- Put capital letters at the beginning of sentences, especially in the comments.
- There are two objects in lowercase while the others are in PascalCase, unify them in PascalCase, a project with coherence makes it immediately more professional.
- Between the rounds, there is no waiting time. It's that goes immediately to the enemy, if you don't want to put a pause time, I understand. In this case, set in the centre of the screen that it's now the enemy's or the player's turn, display it for a few seconds and hide it.
You will say it is ridiculous it is already displayed, yes, but that does not present as a game, it is not ludic. An example after presenting a feature also presents a type of game. I think that this example lacks the basics of the information that can have a turn-based game.

I don't want to sound mean, I know there is a desire to do well and help others by posting this example. It's also my goal, to have an example project that looks pro and is consistent with what it promises, then that is pleasant to play and see while respecting a minimum of turn-based games standards.

I don't do feedback like that to hurt people, but to have a higher and more professional quality level.
Don't take it personally, it's just a review of a project.
I would be happy to continue the feedback with you in order to have a final rendering that I could accept without any problem in accordance with the required quality level.

**Comment by shadow00dev** [comment]
> The idea of a Start scene is interesting. I was thinking about a redesign of the presentation to make the project more attractive. I strongly suggest using objects/textures from the asset store because there are icons and buttons. It gives a style and a certain cachet to the example. If you want my personal opinion, it is not presentable. That's why I'm pushing to have a minimum interface with sprites from the asset store.
> 
> > the only changes I haven't done is FSM and didn't use the asset store but I did change the art a little
> 
> I'm probably annoying, but the quality is essential. An example should be representative of the software and the games that are possible.
> 
> I see that you have indeed made some changes, continue the changes, it's on the right track!
> 
> * I see that there is at least one object not used, it has a default name.
> * Click to start, is not centred.
> * Use groups in the events, it makes the project much more structured.
> * Put capital letters at the beginning of sentences, especially in the comments.
> * There are two objects in lowercase while the others are in PascalCase, unify them in PascalCase, a project with coherence makes it immediately more professional.
> * Between the rounds, there is no waiting time. It's that goes immediately to the enemy, if you don't want to put a pause time, I understand. In this case, set in the centre of the screen that it's now the enemy's or the player's turn, display it for a few seconds and hide it.
>   You will say it is ridiculous it is already displayed, yes, but that does not present as a game, it is not ludic. An example after presenting a feature also presents a type of game. I think that this example lacks the basics of the information that can have a turn-based game.
> 
> > i would of probably done it anyway(for the itch.io page to make it better) but okay, also this is the first time for this and I haven't done game dev in about a year and then i see that someone needed help i made a "crappy" example for him then made this one cuz i wanted to make it better so this is it i guess, also I'm not that good at explaining stuff to tbh
> 
> I don't want to sound mean, I know there is a desire to do well and help others by posting this example. It's also my goal, to have an example project that looks pro and is consistent with what it promises, then that is pleasant to play and see while respecting a minimum of turn-based games standards.
> 
> I don't do feedback like that to hurt people, but to have a higher and more professional quality level. Don't take it personally, it's just a review of a project. I would be happy to continue the feedback with you in order to have a final rendering that I could accept without any problem in accordance with the required quality level.

I don't take it personally, also okay ill get to work on changes

**Comment by shadow00dev** [comment]
also i do use groups in the project to structure it btw(well I structure it different prob but I do use them for that reason)

**Comment by Bouh** [comment]
> also i do use groups in the project to structure it btw(well I structure it different prob but I do use them for that reason)

You can add groups, for white comments ;)
Think major caps at beginning of the sentences in groups/comments.

**Comment by shadow00dev** [comment]
> > also i do use groups in the project to structure it btw(well I structure it different prob but I do use them for that reason)
> 
> You can add groups, for white comments ;) Think major caps at beginning of the sentences in groups/comments.

okay

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7262794/TurnedBasedFighting.zip)
here it is the only thing i did to is say the turn in the center of scene(mainly because when i tried it was very buggy and it made no sense to me to why(because it was happening even when i told it not to))

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7262818/TurnedBasedFighting.zip)
sorry for another uplaod but i find a issue with the last one(ik i should of checked and i did maybe the tired got to me then but when i realised i fixed the issue(issue was 2 images that were not used were there))

**Comment by shadow00dev** [comment]
FSM I will do I guess, thought I'm pretty sure there aren't any unused events?

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7380646/TurnedBasedFighting.zip)

here is the update with the changes the only thing I didn't change is the flip event stuff since i personally think it would be more helpful for some stuff(like if someone wanted to edit the level or add they're own they could use the flip event to change the player and enemy around or somthing i guess)

**Comment by D8H** [comment]
> also wheres the typo for the Game variable?, i cannot find it , also i have one idea to remove the playerusedabitly

![image](https://user-images.githubusercontent.com/2611977/138109348-2b60562d-759c-4a90-9568-acb9b6c0ddb2.png)

> i got an idea for less variable for randomhelp but it would use a exetension so would that be okay?

It's ok to have a lot of variables. I think we can take a look on this after the states are all in place.

> how could i replace the playerusedabitly?, cuz the "State" wouldnt be able to do that cuz of how the system would work right? cuz the "State" was only meant to be a "Turn" orginally

It will probably be more difficult than for the `"GameOver"` state. The `"PlayerTurn"` state could probably be split in 2 states:
* `"WaitingPlayerInput"`
* `"PlayerAttack"`

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7383202/TurnedBasedFighting.zip)

I think you meant something like this so i did it

**Comment by D8H** [comment]
Yes, you can also move the action to change the displayed test. It will need a new scene variable to know who win, but that way everything about the game over will be at the same place.
If one day someone wants to change the look of the game over, only what's inside the `"GameOver"` state will have to be modified.

**Comment by shadow00dev** [comment]
in theory it wont need a variable. i would just need to check whoes at 0 hp, right?

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7383535/TurnedBasedFighting.zip)

here it is(im not 100% sure if this is it but its what i think you wanted me to do for this)

**Comment by D8H** [comment]
> > The events that check if players are dead are outside of the states. We know that the player only takes damage during the `"EnemyTurn"` state so it can be checked there (and the other way around).
> 
> i dont understand this, dont the dmging system for it work good right now so no need to change?

Because they are state transitions. It's important that they are in a state.

It should be something like this:

![FiniteStateMachine](https://user-images.githubusercontent.com/2611977/138168008-c1ded56c-0adc-4cda-868f-fdb8f8c646e5.png)

An arrow (transition) must come from a state to go to another one.

Then we will add more states if needed.

> > There should not be any event outside a state other than "At the beginning of the scene" (which can be seen as an state too) or things that can happen anytime like a pause or a game menu.
> 
> i dont understand what i should change?, if i put the timer inside the State enemy and player turns then i feel like i shouldnt tbh

Yes, this event is fine outside because it's to handle an animation end. To make it easier to understand what it does. You can set the animation 1s long (it might need 2 frames, I'm not sure) and check when it ends to go back to the "Idle" animation instead of using a timer.

**Comment by shadow00dev** [comment]
> > > The events that check if players are dead are outside of the states. We know that the player only takes damage during the `"EnemyTurn"` state so it can be checked there (and the other way around).
> > 
> > 
> > i dont understand this, dont the dmging system for it work good right now so no need to change?
> 
> Because they are state transitions. It's important that they are in a state.
> 
> It should be something like this:
> 
> ![FiniteStateMachine](https://user-images.githubusercontent.com/2611977/138168008-c1ded56c-0adc-4cda-868f-fdb8f8c646e5.png)
> 
> An arrow (transition) must come from a state to go to another one.

that's what my events do?,(sorry for the late answer), i don't feel like i need to change anything cuz that image is basically what the state stuff of my events do unless im wrong?

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7384447/TurnedBasedFighting.zip)

this is with the changes to how animation changes to idle(aka removed the timer)

**Comment by D8H** [comment]
> the ones in red square makes no sense todo, cuz the the ennitiys one would be for both player and enemy states(so i would have to put them in a state for not gameover which would be variable state not game over right.

You are right that reducing the number of events can be a good thing, but this is not the only thing that make good events. Clarity, bug proofness, performances are important too.

On the clarity part:
* It makes it clear that the transition is, for instance, from PlayerTurn to GameOver.
* The reader will see the event that make damages and then the one that checks the game over.
* The reader doesn't have to know what objects there is in the "Entity" group as "Player" and "Enemy" are used directly.

On the bug proofness part:
* When an event is inside a state, it's less likely to make strange effects during another state because it can't be executed.

On the performance part:
* The events are only executed during one state (it can even be done only when damages are taken, but we will come back to this later). So, it uses less CPU. In this particular case, it won't make much a difference but we need to set an example for bigger projects that will do need good optimizations.

> For the beginning of scene one thats like that to, cuz its for the group it in, it would make no sense to put it in scene group, right?

When the event groups follow the stats there won't be any "Scene" or "Entry" groups. It should be something like this:
* Beginning
* Always
* Player Turn
* Enemy Turn
* Game Over

The health bar events are not in the right state. The player health change during the the EnemyTurn state.

You didn't do the TODO in the middle of the screenshot.

**Comment by D8H** [comment]
> what else i need to fix/change?

* The transition to the "GameOver" state need to be inside the states it happens.
* Use one event groups per state, for instance:
  * Beginning
  * Always
  * Player Turn
  * Enemy Turn
  * Game Over
* Try to spit PlayerTurn and EnemyTurn (see the drawing and explanation above)

**Comment by shadow00dev** [comment]
> > what else i need to fix/change?
> 
> * The transition to the "GameOver" state need to be inside the states it happens.
> * Use one event groups per state, for instance:
>   
>   * Beginning
>   * Always
>   * Player Turn
>   * Enemy Turn
>   * Game Over
> * Try to spit PlayerTurn and EnemyTurn (see the drawing and explanation above)

so like new states?

**Comment by D8H** [comment]
> > * Try to spit PlayerTurn and EnemyTurn (see the drawing and explanation above)
> 
> so like new states?

Yes, it's at the end of this message: https://github.com/GDevelopApp/GDevelop-examples/issues/121#issuecomment-949091777

**Comment by shadow00dev** [comment]
okay

**Comment by shadow00dev** [comment]
anyway ig ill do it tomorrow since its a bit late rn(but it still makes no sense for me to do dis in my opinion cuz it works and its has a order(like the comments and the groups gives it order))

**Comment by D8H** [comment]
> 
> 
> > * Use one event groups per state, for instance:
> >   
> >   * Beginning
> >   * Always
> >   * Player Turn
> >   * Enemy Turn
> >   * Game Over
> 
> Beginning isnt a state its a on beggining of scene(right?) and always isnt a state to right?

The beginning of scene is the initial state in some way, but yes. Yes, "Always" is like a factorization instead of copy pasting it in each state.
It just to make it clear when the events can happen.

**Comment by shadow00dev** [comment]
@D8H may I ask you to make sure the changes for music and sounds are good, please?

**Comment by D8H** [comment]
I did a step by step review for the FSM because it was too big of a change to explain it all at once. But, for the polishing, I will only do a final review when you think everything is ready.

**Comment by shadow00dev** [comment]
that update was my latest update for stuff i wanted to do, so i think everything is ready for the polishing i guess

**Comment by shadow00dev** [comment]
@D8H  can you please give a list of stuff for me to do with polishing please(i know i pinged you again and sorry, but sometimes i get worried and Want to finish it as soon as possible(hence why i try to answer as quickly and i can) i do find working on this fun but i dont know what else to do maybe remove the info text but that's all i can really think off)

**Comment by Midhil457** [comment]
Hi, I can't do a full review cuz I am not on my system and having to use the web app, which for some reason can't load the resources and I have some limitations with time :(. (I haven't gone through the 156 😱 message, so some of them might be already suggested)

- The package name should be `com.gdexample.<projectname>` as all the example's package name was recently updated to use that format to prevent any conflicts
- The desktop icons seems to be the same as the thumbnail image. But, a separate image is used. You can use the thumbnail for the icon too
- `CenterX()` and `CenterY()` is now preferred more than ` PointX("center")` and ` PointY("center")`

![trn-3](https://user-images.githubusercontent.com/73597906/139801232-6b8fa56d-1e16-418f-bdf9-08059e917ecb.PNG)
- This format should in theory work as the mouse conditions are compatible with a touch screen
![trn-1](https://user-images.githubusercontent.com/73597906/139800496-0d636afc-d22b-41de-84b2-85d3fe6510fa.PNG)
- What is the use of picking all `PlayControls`?
![trn-2](https://user-images.githubusercontent.com/73597906/139800545-b388a503-ba8b-4815-a9c1-e945b0d9389f.PNG)

:)

**Comment by shadow00dev** [comment]
okay and for the pick all condition, idk tbh, originally i changed both button but this doesn't

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7463384/TurnedBasedFighting.zip)


![Screenshot 2021-11-02 185842](https://user-images.githubusercontent.com/45771918/139927979-09191515-cbf3-41e7-9a69-2b4eab67fc89.png)

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7463397/TurnedBasedFighting.zip)

fixed the 2 images not being in the right place and removed red text stuff from resource tab

**Comment by shadow00dev** [comment]
@D8H please can I ask for you to tell me what to change(cuz really wanna get this finished and umm idk)

**Comment by D8H** [comment]
I'm working on the platformer behavior. I'll try to take a look in a few days.

**Comment by shadow00dev** [comment]
okay

**Comment by D8H** [comment]
* I made a typo in this comment: "Marck [Mark] a pause before choosing an attack"
* The text color could be the same hue as a color from the back ground. For instance, the blue of the moon holes is ABD7FF.
* The game over mask opacity can be raised to 196 to have enough contrast with the text.
* Characters should be the same distance from the center of the screen. Maybe nearer to the center than currently.
* The health bar color is really flashy. I could be a bit darker and less saturated.

**Comment by shadow00dev** [comment]
> * I made a typo in this comment: "Marck [Mark] a pause before choosing an attack"

so like i show the pause?, okay

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7479116/TurnedBasedFighting.zip)
![Screenshot 2021-11-04 215407](https://user-images.githubusercontent.com/45771918/140425652-92f08d85-7c43-4251-9752-8e988a4df778.png)

**Comment by D8H** [comment]
> > * I made a typo in this comment: "Marck [Mark] a pause before choosing an attack"
> 
> so like i show a pause?, okay

* It's just a "c" to remove in a comment from EnemyChoice.
* The health bar is hard to see now. Maybe this color: b41818?
* The button should probably be under the character like before.

**Comment by shadow00dev** [comment]
> * The buttons should probably be under the character like before.

i never changed the position of them :|



> * It's just a "c" to remove in a comment from EnemyChoice.

sorry idk what that means, i remove "c from comment?, ill check them to see if i can understand



> * The health bar is hard to see now. Maybe this color: b41818?

okay

**Comment by shadow00dev** [comment]
![Screenshot 2021-11-05 145514](https://user-images.githubusercontent.com/45771918/140530833-6e339d0e-7c26-484c-aace-9e47be091b4e.png)

for mobile at least i personally would hate playing it like this tbh(the controls were where i put them cuz its nice and easzy to touch them on mobile devices) i will only do it if you want me to and i mean like if you say do it (not a maybe do it cuz i dont like it so i dont really want to but i will if you tell me)

**Comment by shadow00dev** [comment]
> * It's just a "c" to remove in a comment from EnemyChoice.

ooh i see now ill give you thefiles for the changes as soon as i can(like right now almost) but i didnt change pos of buttons since i dont like the idea of it personnally

**Comment by shadow00dev** [comment]
[TurnedBasedFighting.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7486906/TurnedBasedFighting.zip)

Also Sorry for super late aswer i was asleep then i think(or didnt check github) 

all i changed was color of health bar to b41818
and remove c from marck in the comment inside enemychoice

**Comment by Midhil457** [comment]
Hi, sorry I can’t do a proper review. But,
See if your example follows the best practices, http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example#best_practices
Don’t know if someone already suggested it in the 157 message so 😅

**Comment by shadow00dev** [comment]
> Hi, sorry I can’t do a proper review. But, See if your example follows the best practices, http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example#best_practices Don’t know if someone already suggested it in the 157 message so 😅

i have read this before and i think when doing the major changes in event it was kinda(unkownly) following it(well if i remeber correctly)

**Comment by Midhil457** [comment]
Hi,  I wasn't able to find much issues. but, there are a few that I missed from the last review (sorry btw for missing them), Great project btw
- The README `this is a turned based fighting example game, this example game works on mobile and computer
also, this example uses assets from Kenney and pzUH, sound effects made with bfxr, and music made with  chrome music lab` could be changed to `A simple turn based fight game where the player battles with a bot` and the long description being ` The example work on both on a mobile and a computer. The example uses assets from kenney assets and pzUH. The Sound effects are made using bfxr and chrome music lab`. You can add a long description by leaving a space between the short and long description
- This is just a suggestion, for the flash effect, you could use the flash extension instead of using events to make the events simpler
- You add spaces in the project name
- A mistake on my behalf, the package name should be `com.example` and not as what I suggested, this is more preferred. I am extremely sorry for the mistake :sweat:

:)

**Comment by shadow00dev** [comment]
> * This is just a suggestion, for the flash effect, you could use the flash extension instead of using events to make the events simpler

1. last time i used that extension is was not working for me

2. i thought the less extensions the better

3. im also not a giant fun of using extensions

4. i think its easy to do??

if you still want me to do it i will

for the rest, okay also im not good at typing stuff and that so um yah(may i use what you put to put in readme?)

**Comment by Midhil457** [comment]
Yes, feel free to use the one i suggested in the readme

**Comment by shadow00dev** [comment]
Thanks :)

**Comment by Midhil457** [comment]
Hi,
I have made a few changes to the project (like changed project's name to `Turn Based Fighting` and more) and submitted a PR. 

Thank you for the great example!

**Comment by shadow00dev** [comment]
okay thanks

**Comment by Bouh** [comment]
Closed by https://github.com/GDevelopApp/GDevelop-examples/pull/165
