### ISSUE TITLE
New example: Fixed Camera Transitions [Using Tweens]

### ISSUE THREAD

**Issue by Elairyx7301** [GDevelopApp/GDevelop-examples#149]
## Describe the example

This example showcases fixed screen transition. Whenever the player moves outside of the current frame, the camera smoothly moves one room in that direction.
A rather easy but sweet event prevents the player from leaving the scene when a transition is happening. Even though this might be most suitable for a Top-Down game, this example shows that it can also find application with other game styles as well.
This is just a template and can be modified freely to fit the personal needs or match the game's style and/or atmosphere.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[FixedMoveTransitions.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7461229/FixedMoveTransitions.zip)
![image](https://user-images.githubusercontent.com/83909121/139862428-0ce20b40-6c53-4730-8e7d-1389caf9a8a9.png)

**Comment by Midhil457** [comment]
Hi, here is my short review,
- There are broken resources in the resource manager, please fix them
- Hide is not a good name for a object group. Maybe `HiddenObjects` is a better naming
- `placeholder` might be better than `helper` for the resource name
- `Xaxis` and `Yaxis` is a better name than `horizontal` and `vertical` in my opinion as it is better to follow directional names used by the engine (to keep it simple)
- The package name needs to be `com.gdexample.<project name>`.  The format was recently changed so that the examples don't accidentally conflict with the games made by users (Which have `com.example` as default`) and also to be able to differentiate the examples
- The `README` could get some changes. The short description should explain *what the example* does and not *how the example does it*. The `Topdown adventure camera` does the similar thing with the camera, you could look into that. Also for adding a long description, leave a line between the short description and it should be considered as the long description
- I don't think `Fixed Move Transition` is the right name for this example. Maybe `Room Camera`? I don't have many suggestions
- The project is very lagging for me. Might be because of the duct tape setup I am using so that I can do the review, but the other examples do seem to be a bit more smoother

:)

**Comment by Elairyx7301** [comment]
@Midhil457 Thank you for that big review!

For me, the project is running smoothly and is at a constant 58 to 60 fps without any lags. I've added a fps counter, maybe you can check with that again. I have noticed the "Top-Down Adventure Camera" example but the main differences are that this is a platformer project using Tweens instead of the lerp() expression method.

## Done changes
- broken resources fixed
- renamed group to `HiddenObjects `
- renamed `helper` to `placeholder`
- changed `Horizontal Transition` to `X-Axis Transition (horizontal)`
- changed `Vertical Transition` to `Y-Axis Transition (vertical)`
- Added several comments for clarity
- Removed redundant object variables
- Slightly improved event structure
- Changed `README`. I'm not entirely sure what you said to change but I tried my best to improve the wording.
- Changed `Fixed Move Transition` to `Fixed Camera Transition` in several places
- Changed UI text color for clarity
- Moved cameraCenter instance into frame
- Updated project version to `0.0.3`
- Added key commands like `R` to reset and `LControl` to toggle debug
- Added total time (time from start, floored) and FPS counter
- Added drop shadow to UI text for clarity

## Version 0.3
v0.1: See original issue
v0.2: Never publicly released
**v0.3:** [FixedScreenTransition0.3.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7522227/FixedScreenTransition0.3.zip)

Please ping me here or on Discord if there are other needed changes to make etc. :)

**Comment by Midhil457** [comment]
- It's recommended to initialize the variables in the variables dialog and not in the event sheet
 
- Why have it update using a timer? Use `"FPS: " + ToString(round(10/TimeDelta()/10))` so that the value doesn't change quickly making it unreadable.
![fct-1](https://user-images.githubusercontent.com/73597906/141982272-0b047193-37ed-49a6-b6d3-fabdb7d79265.png)
- `Horizontal` and `Vertical` naming is still used for the tween identifier
![fct-2](https://user-images.githubusercontent.com/73597906/141982412-71b13ebb-8844-4f6c-9ae3-631c60bc870b.png)
- Use release instead of `pressed` and trigger once
![fct-3](https://user-images.githubusercontent.com/73597906/141982559-75355a24-8ca1-4a3e-94bb-3613669e7300.png)
- The purple comments are a bit hard on the eyes, maybe change them to a color that doesn't stick out much. Maybe the default?
- Remove the spaces in scene names, they might cause issues in the later version if any big changes occur
- I found this comment:
`Personally, I like to separate the variable setup from everything else like visiblitly, Z-Order, position, opacity etc..
This helps with clarity in bigger projects. This is why this event exists and the actions are not in the main event straight away.`
A bit unnessesary

:)

**Comment by Elairyx7301** [comment]
Thank you @Midhil457 again for the review!
I have made the changes you recommended.

> so that the value doesn't change quickly making it unreadable

Understandable.
That's why I had used a timer in the first place.
-> Changed anyway

> Make the version number 1.0.0 and no don't increment it after every change

That is my understanding of it as well and I prefer that method but I've been "told" (rather shown) differently in other issues and submissions, that's why I adapted to that format in this submission as well.
-> Changed to 1.0.0

## v1.0.0 - Done changes
- Variable declaration/initialization
- Renamed "moveCamVERTICAL" to "moveCamYAxis"
- Changed "key down once" to "key released"
- Changed comment color from purple to yellow
- Removed spaces in scene name
- Removed two comments
- Capitalized object names

## Files

[FixedScreenTransition1.0.0.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7547001/FixedScreenTransition1.0.0.zip)

**Comment by Midhil457** [comment]
Your zip only contains the json file. PLease include the whole project for easy review :)

**Comment by Elairyx7301** [comment]
Very sorry for all the bad mistakes and caused inconveniences ~~(as usual)~~ 😅
[FixedScreenTransition.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7555365/FixedScreenTransition.zip)

**Comment by Midhil457** [comment]
Thank you for your contributon!
A PR has been created and will be merged (if everything goes well) soon.

I have changed the example's name to `Platformer Room Camera`so that users can easily figure out what the example does. Hope you don't mind :)

**Comment by Elairyx7301** [comment]
Thank you for the reviewing effort and for opening the PR!
