### ISSUE TITLE
Spider Web - Example

### ISSUE THREAD

**Issue by SashaWerto** [GDevelopApp/GDevelop-examples#160]
- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this gam
e and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.
Update 2.0 : [SpiderExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7611910/SpiderExample.zip)

**Comment by Midhil457** [comment]
Hi,
- The issues I have found with the project are mentioned in the best practices. Please follow it http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example#best_practices

- It's hard to start the game as the spider is constantly falling and making it hard to catch a bug

:)

**Comment by SashaWerto** [comment]
https://github.com/GDevelopApp/GDevelop-examples/issues/160#issuecomment-970272388
Hi,
I updated the example, can you check it please ?

**Comment by Bouh** [comment]
Here a new review:

- [ ] Resource are broken because of cyclic characters
![image](https://user-images.githubusercontent.com/1670670/142284665-0bcdffb0-f3ec-4418-9c57-8be517cdb62d.png)
- [ ] `com.gdexample.spider_example` -> `com.example.SpiderExample`  @Midhil457 We use `example` instead of `gdexample` right?
- [ ] The game name has an underscore is it your wish? `Spider_Example`
- [ ] The game resolution is not conventional is it normal? `1280x920`
- [ ] The spider is constantly falling, even when a Fly is hooked. There is something to change in gameplay to make it playable.
- [ ] What is the objective of this game? How to play? What are the inputs to use? What is for the text object on the top-left corner?
Don't answer me here, it should be added to the game because it should be implicit when running the example.
- [ ] `Coursour` object -> `Cursor`
- [ ] Some animation of the Player and other objects are never used. Delete the unused animations, the unused sprite that goes with it in the folder and unused sprite in the resource list with a right-click ;)

Cool art and animation! 
There is interesting gameplay to play with the spider, I think.

**Comment by SashaWerto** [comment]
> Here a new review:
> 
> * [ ]  Resource are broken because of cyclic characters
>   ![image](https://user-images.githubusercontent.com/1670670/142284665-0bcdffb0-f3ec-4418-9c57-8be517cdb62d.png)
> * [ ]  `com.gdexample.spider_example` -> `com.example.SpiderExample`  @Midhil457 We use `example` instead of `gdexample` right?
> * [ ]  The game name has an underscore is it your wish? `Spider_Example`
> * [ ]  The game resolution is not conventional is it normal? `1280x920`
> * [ ]  The spider is constantly falling, even when a Fly is hooked. There is something to change in gameplay to make it playable.
> * [ ]  What is the objective of this game? How to play? What are the inputs to use? What is for the text object on the top-left corner?
>   Don't answer me here, it should be added to the game because it should be implicit when running the example.
> * [ ]  `Coursour` object -> `Cursor`
> * [ ]  Some animation of the Player and other objects are never used. Delete the unused animations, the unused sprite that goes with it in the folder and unused sprite in the resource list with a right-click ;)
> 
> Cool art and animation! There is interesting gameplay to play with the spider, I think.

![image](https://user-images.githubusercontent.com/46349695/142299328-bed709c1-8a02-4507-9898-3fb6c390447c.png)

Now there is a goal in the game.
Added main menu
Changed the name of sprites and sorted into folders
Game resolution fixed
Changed project name and com.example
Removed unused sprites as well as cleaned resources from lost sprites

*Updated the file to the new version

**Comment by shadow00dev** [comment]
(I know I'm not a reviewer  but I wanna help so here is some feedback)

there is a bug where sometimes the web doesn't register the platforms
and it would be nice if gravity were not a thing if player was eating a fly(it would make it easier to play but that's up to you)
also I don't think s is a control(I think this cuz I don't see any needs for it when I play it) maybe make it so so s can go down a web(cuz w can go up a web)

**Comment by Bouh** [comment]
I've made changes and simplified a lot of things on animations, finite state machines, cleaning, and reducing events.

[SpiderExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7609158/SpiderExample.zip)

**Comment by Midhil457** [comment]
I have also made some changes and fixes
Notable ones:
- Remvoe the file names enetered in teh icons field
- Remove the Debug text and only create it when debug is on
- Add Cursor to the scene instead of creating it


[SpiderExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7611624/SpiderExample.zip)

:)

**Comment by SashaWerto** [comment]
the changes you made, the movement of the spider is extremely limited, as well as he now sometimes can not jump while running and can not swing on the web ... This is not what I wanted to achieve.

**Comment by SashaWerto** [comment]
> I've made changes and simplified a lot of things on animations, finite state machines, cleaning, and reducing events.
> 
> [SpiderExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7609158/SpiderExample.zip)
> 
> Try it, if it's good for you let me know and I merge.

Can I return the previous control to the spider ? Because the changes you made, the movement of the spider is extremely limited, as well as he now sometimes can not jump while running and can not swing on the web ... This is not what I wanted to achieve.

**Comment by SashaWerto** [comment]
> I have also made some changes and fixes Notable ones:
> 
> * Remove the file names entered in teh icons field
> * Remove the Debug text and only create it when debug is on
> * Add Cursor to the scene instead of creating it
> 
> [SpiderExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7611910/SpiderExample.zip)
> 
> **Bouh's edit: First post updated with files.**
> 
> :)

Thanks :)

**Comment by Bouh** [comment]
[SpiderExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7613950/SpiderExample.zip)

**Comment by SashaWerto** [comment]
> [SpiderExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7613950/SpiderExample.zip)

Thank you very much. Sorry if I wasted your time.

**Comment by Bouh** [comment]
Added in https://github.com/GDevelopApp/GDevelop-examples/pull/174
Soon available in the application, thank you @SashaWerto for your new example!
