### ISSUE TITLE
Modern Asteroids

### ISSUE THREAD

**Issue by charburgx** [GDevelopApp/GDevelop-examples#176]
## Describe the example

This is an implementation of asteroids with nice graphics, sounds, etc. Intended to be used as a starter and/or for official tutorial videos.

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

[modern-asteroids.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7620291/modern-asteroids.zip)

**Comment by 4ian** [comment]
Thanks for making this 👍👍
Overall the quality of this is very good. I think this is better than a traditional asteroid game and we can feel the game is more "juicy", which is exactly what we're searching for. Notably:
* Game Over text with the effect and the sound effect: great stuff!
* Using the physics engine for colliding with the asteroids, great idea! Give a real good feeling to the game!!
* Physics engine for control is also "juicy" and fun.

Small adaptations that I've noted:
* No asteroids on the right hand side of the window? It's always empty there for me
* You should not need a Trigger Once for these:
  ![image](https://user-images.githubusercontent.com/1280130/143955771-7515d724-2947-489c-b3f5-143ccc25c1af.png)
  BUT you should need a for each object AsteroidBig in theory to be sure you handle the proper deletion of multiple AsteroidBig, should there be more than one at the exact same frame (let me know if you want more explanation on this).
* Delete bullets after a while (otherwise you can fill the screen of bullets). If we do this, I recommend to have a behavior "DeleteAfterDuration" which automatically launch a timer at object creation and then delete the object when the timer has passed a certain amount of time (10 seconds by default). So adding this to the bullet is just a few clicks!! :) 
  * I recommend doing this. It's a good habit to delete objects like bullets. And this is a good exercice to make this behavior ;) 

Potential larger improvements:
* Check if you can use a behavior to wrap the objects. Otherwise, at least have the group EVERYTHING renamed to Everything (all names are PascalCase in GDevelop by convention). Or better, rename it to something like "Solid" (this represents a group of solid objects).
  * There is https://wiki.gdevelop.io/gdevelop5/extensions/screen-wrap/reference, but it does not work well it seems! We should improve the behavior I think.
* When you have the game over screen, you can still fire bullets. Could be cool to avoid this.
* And finally... could we have mobile controls? 😄 
  * I know this is a larger improvement, but might be worth talking how we could do this quickly. Add a few UI controls, hide them if keyboard supported, and otherwise support them in events (that's a bit of rework... we could see if there is an easier solution).

**Comment by charburgx** [comment]
[Asteroids_GDevelopExample (2).zip](https://github.com/GDevelopApp/GDevelop-examples/files/7677326/Asteroids_GDevelopExample.2.zip)

Here is the fixed version, incorporating those changes!

**Comment by Bouh** [comment]
The screen wrap works on mobile but with a larger width/height out of the screen.
In summary, the player and asteroids can go off-screen on a few hundred pixels before poping on the opposite side.
