### ISSUE TITLE
Linked Chain demo

### ISSUE THREAD

**Issue by HardTranceFan** [GDevelopApp/GDevelop-examples#271]
This example is a demonstration using the Physics2 revolute joint to link together a number of objects to create a chain like effect.

## Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [X] My game has a proper name in the game properties. 
- [X] My game package name behind with `com.example.`.
- [X] My game has all events unfolded.
- [X] I've added myself as the author in the game properties.
- [X] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [X] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I've cleaned unused resources.

## Game folder

[ChainPhysicsDemo-revolute.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8600407/ChainPhysicsDemo-revolute.zip)

**Comment by Bouh** [comment]
Hello @HardTranceFan 
Thank you for this project! Here what I've seen during my review:

- [ ] An image is broken in Animations of the **chainLink1** object, same for **chainLink2**:
![image](https://user-images.githubusercontent.com/1670670/166671662-074e2b0b-5968-41b9-9ba3-ccb28b52f161.png)

- [ ] README content can be shorter : ``` This example is a demonstration using the Physics 2.0 and the revolute joint action to link together a number of objects to create a dynamic chain with a realistic physic.```
 We don't add requirement in this readme, it should be explain in the example itselft in a comment for example.
- [ ] To optimize a bit the physic because it could be costly in a larger example with tons of chains, you can check the Can sleep box in Physics 2.0  behavior for all object using the physics. It will stop the simulation of the physics when it need, (when the movement is over).
 - [ ] On objects text, add a period or not on both.
 - [ ] Our variables start by an underscore which is not required at all, I think you can remove this underscore, we strongly recommand the `PascalCase` syntax.
 - [ ] Objects must use `PascalCase` too.
 - [x] Ressources are in an assets folder
 - [ ] Comment ```This action puts a revolute joint between chainLink2 and the next chainLink1. If the next chainLink1 doesn't exits, then _isStillProcessing remains false.``` is nice. Can you add in this comment why we want _isStillProcessing false, please, to remind people what is for.
 - [ ] Comment just below ```Once all the chain links have **bee** joined, ``` **bee** ? Typo?
 - [ ] `_jointId` variable is a scene variable used for mouse, I think we should rename it to be more explicative like `MouseJointId`
 - [ ] On last condition you use `Escape key is pressed` I recommand to choose **is released**, because when you stay on escape key it restart the scene, and in this new scene it detect the escape key pressed, and it loop for ever while you press escape. Compared to **is released** where the event is detected once, when you release the key, and there is no more loop.
 

Cool use of the while loop with stillProcessing variable!

 Overall this example is well made and documented, really a great job done here!
Before another review from someone else I think you can try to apply these first feedback, and then someone else will give a new look after.

**Comment by HardTranceFan** [comment]
Hi @Bouh,

I'm going through the check list, and I'm not sure what you mean with resources are in asset folder. Should they not be in the folder, and moved one level up instead?

Jeroen

**Comment by Bouh** [comment]
> Hi @Bouh,
> 
> I'm going through the check list, and I'm not sure what you mean with resources are in asset folder. Should they not be in the folder, and moved one level up instead?
> 
> Jeroen

On contrary, everything is ok with the asset folder, there is nothing to do. (I try to reuse a genric checklist for faster review on examples)

**Comment by Bouh** [comment]
Hi @HardTranceFan Do you need more time or help?
Let us know ;) !

**Comment by HardTranceFan** [comment]
Hi @Bouh, no, I was waiting for your reply. For some reason it hadn't come up a week after I sent my response.

I'm looking to slightly modify the example, only adding a rope segment sprite for each chain link, so the images  can be switched from chain to rope.

I'll post the update within an day or so.

**Comment by HardTranceFan** [comment]
Hi @Bouh, 

I've updated the project as per checklist. I've also added an extra rope animation for the link, along with a text object that acts as a button to switch between linked chain and rope segments.

Cheers
Jeroen

[ChainPhysicsDemo-revolute.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8770488/ChainPhysicsDemo-revolute.zip)

**Comment by Bouh** [comment]
> Hi @Bouh,
> 
> I've updated the project as per checklist. I've also added an extra rope animation for the link, along with a text object that acts as a button to switch between linked chain and rope segments.
> 
> Cheers Jeroen
> 
> [ChainPhysicsDemo-revolute.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8770488/ChainPhysicsDemo-revolute.zip)

Thank you, I merged your example in https://github.com/GDevelopApp/GDevelop-examples/pull/294 .
I just made one edit to remove the unused scene variable.

Again thanks!
