### ISSUE TITLE
Example update - Text entry

### ISSUE THREAD

**Issue by Bouh** [GDevelopApp/GDevelop-examples#31]
## Describe the update

From https://github.com/4ian/GDevelop/issues/2705

>I edited the description text, and added another scene with comments for mobile input.
>[Forum request](https://forum.gdevelop-app.com/t/android-virtual-keyboard-issue/33124/3)

## Game folder
[My project30.zip](https://github.com/4ian/GDevelop/files/6594456/My.project30.zip)

@PascalLadalle

**Comment by Midhil457** [comment]
Hi, I checked the project out and here is my review

- The package name is empty. Also, adding the appropriate names in the author section, changing the project name, incrementing version number would also be great

![Prperties](https://user-images.githubusercontent.com/73597906/125165447-89f79880-e1b4-11eb-80be-92547c536442.PNG)


- You can also change the README to also include info about the mobile keyboard

- Also, here is the tiniest thing, change "In this example" to "In this scene". As now this example contains multiple scenes and the comment doesn't apply to all the scenes
![Tiny thing](https://user-images.githubusercontent.com/73597906/125165417-6c2a3380-e1b4-11eb-8d00-97eb92d06a86.PNG)


:)

**Comment by PascalLadalle** [comment]
Thanks for reviewing 👍 
I have updated the example accordingly.
I have removed the .md file and written everything in a readme.txt.
I have also added a button to clear the stored text, and I added an event to close the mobile keyboard, because I noticed two issues:
- the text is not properly erased unless the mobile keyboard is closed.
- the keyboard won't reopen unless it has been properly closed.

[My.project30.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6801974/My.project30.zip)

**Comment by Midhil457** [comment]
Hi, great improvements!

- I think .md is preferred

- I wasn't able to test this out (as the project needs to be loaded on a mobile device to test it), but I think, when X button is clicked, it will change the text to `TAP HERE TO OPEN THE MOBILE KEYBOARD` instead of clearing it. because of these events, 
![Loop](https://user-images.githubusercontent.com/73597906/125312470-eba13980-e351-11eb-8064-a56e0fe37dfa.PNG)


:)

**Comment by PascalLadalle** [comment]
I chose .txt because the .md extension is not natively supported by Windows.
The button clears the content of the text entry, but restores the placeholder text so that the user can tap it to open the keyboard and type again.

**Comment by Midhil457** [comment]
> I chose .txt because the .md extension is not natively supported by Windows.

I think you can open them using NotePad. ALso, I found an online editor for it, https://dillinger.io/

:)

**Comment by PascalLadalle** [comment]
> I think you can open them using NotePad.

Yes, I suppose, I meant that there is no software association by default.


> .md is mandatory afaik to be detected by the uploader script as the example description.

Understood, I renamed the readme to .md. 👌 
[My project30.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6811931/My.project30.zip)

**Comment by Midhil457** [comment]
Perfect! I have made a PR for this. Also, I removed the "Official" from the Project name as it would be obvious if it is found in the program itself

:)

**Comment by 4ian** [comment]
Thank you all for this work 👍
