### ISSUE TITLE
P2P-Networking for 2 or more player

### ISSUE THREAD

**Issue by BackpackerSlash** [GDevelopApp/GDevelop-examples#33]
## I expanded upon Arthuros p2p example

**Description:**
I added a "Broker" and a "Waiter" role to simplify connections between more than 2 players. I also modified the chat to display Usernames.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[p2p-networking-for-2-or-more-players.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6809112/p2p-networking-for-2-or-more-players.zip)

**Comment by Midhil457** [comment]
Hi, great example! 

I would really recommend adding more documentation about the example as this is can be classified as a advanced example. I had some trouble understanding what's going on. It possible even a wiki page would be fantastic, but it's your choice

- I just have some suggestions and bugs I found,
- You can start with having any players
- You can enter a lobby without a name
- You could make ChatBoxSprite in the Chat scene a panel sprite to make the object look more sharp and not stretch
- It looks to me that the external layout "Disconnect" is not being used anywhere, please remove it if it's true
- Maybe displace the buttons in the menu, because when start is pressed, the click also triggers in the menu and quickly goes to the synchronized buttons scene

I have also added some suggstions about the project in this project, 
[p2p-networking-for-2-or-more-players.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6821814/p2p-networking-for-2-or-more-players.zip)

I would recommend going through the events and checking for any improvements that can be done or documenting something that might be hard to understand, not saying that the example is bad, saying because the creator knows the project best

:)

**Comment by BackpackerSlash** [comment]
i am updating the example. i found several things to be improved, some of which take your critic into account. Thank you for that.
Some of your comments i will ignore when i disagree. I hope you don't mind if i do not explain to why.

**Comment by Midhil457** [comment]
I forgot to add a a suggestion,

- Separate texts for these will be fine
![P2p1](https://user-images.githubusercontent.com/73597906/125959999-f4fa60df-0114-4881-8e25-59e76f458cc3.PNG)
:)

**Comment by Jurfix** [comment]
Hello good example! I made some changes to the events of the "Chat" scene, or rather, corrected the removal of the first line if the lines are greater than or equal to 28.
[p2p-networking-for-2-or-more-players.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6950894/p2p-networking-for-2-or-more-players.zip)

**Comment by Jurfix** [comment]
![image](https://user-images.githubusercontent.com/64281856/128635180-e8ae0728-2980-4c46-9411-4de79d48b176.png)
I also recommend that you replace this line with something, because she literally makes you write only in Latin.

**Comment by Bouh** [comment]
This example is a **P2P networking chat**, I suggest renaming it as well
To leave the place for a potential future scalable example where we have multiple players on a playground moving and shooting or whatever, a more advanced POC for P2P. I wish to differentiate between a chat and a game.


@arthuro555 The sanitizer extension prevents writing in Cyrillic and other non-latin languages.

**Comment by Bouh** [comment]
Hi @BackpackerSlash 

- The example didn't work.

![image](https://user-images.githubusercontent.com/1670670/137644412-f983debd-5c91-4ac6-9129-f16a510e9053.png)


- Streched sprite have to be replace by 9-patch object.
- Factorize the group **Copy P2P Adress** in **Wait** Scene, 1 sub-event can be deleted.
- Author name is empty
- The game shoud use the new system for the Z-order (game properties)
- Just delete this line as suggested before
![image](https://user-images.githubusercontent.com/64281856/128635180-e8ae0728-2980-4c46-9411-4de79d48b176.png
)
- Without more change we'll close this submission 31 oct 2021.

**Comment by Midhil457** [comment]
Closing as no updates has been given
