### ISSUE TITLE
Weather Example

### ISSUE THREAD

**Issue by SashaWerto** [GDevelopApp/GDevelop-examples#43]
## Weather Template

This example shows how different weather conditions can be implemented and how they can affect

## Checklist

- [+] My game has a proper name in the game properties. 
- [+] My game package name behind with `com.example.`.
- [+] My game has all events unfolded.
- [+] I've added myself as the author in the game properties.
- [+] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [+] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [+] I've cleaned unused resources.

## Game folder
[Weather_Template.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6874645/Weather_Template.zip)

**Comment by Midhil457** [comment]
Hi, great example

- There are a lot of invalid resources, please remove them
![Weather_1](https://user-images.githubusercontent.com/73597906/127731228-d0c2c891-2ac5-4c59-898f-635592774912.PNG)
- Both the rain and snow weather change the text to `Snow`
![Weather_2](https://user-images.githubusercontent.com/73597906/127731231-fe8f9157-d29f-42e0-8a1b-83a17d275cac.PNG)

- Use a tiled object for Platform instead of many sprites
- Name the assets better than `NewObject -1` etc...
- The README file could be ` An example that implements weather including rain, snow, wind, etc...
- Use event groups instead of comments and nested events
- The camera zoom only needs to be set at the beginning of the scene instead of running all the time
- I don't see any harm  in turning on `default controls` in the platformer behavior

:)

**Comment by Bouh** [comment]
Closing this due to non-response after 30days.

@SashaWerto if you are still interested in adding this, please apply the reviews and I'll reopen this feed.
