### ISSUE TITLE
Car Physics Joint Demo, mobile & pc

### ISSUE THREAD

**Issue by frolics2dio** [GDevelopApp/GDevelop-examples#47]
## Car Physics Joint Demo

A realistic physics car demo that allows you to enjoy testing a car physics in gdevelop.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[Car Physics Joint Demo.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6899971/Car.Physics.Joint.Demo.zip)

**Comment by Midhil457** [comment]
Hi, great changes! 

- The car automatically moves when `start engine` is pressed, is this intentional?
- The README file could be `A fun realistic physics based car example`

I have included the events suggestion in this copy: 
[Car Physics Joint Demo_withSuggestions.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6910857/Car.Physics.Joint.Demo_withSuggestions.zip)

:)

**Comment by Bouh** [comment]
Awesome game!

- [ ] I got stuck on the "Start engine" and "Stop" buttons. These should be gray out or made clear that they are not usable before making a choice between "Keys" or "Touch".
- [ ] **Car physics** logo on top left corner isn't mandatory
- [ ] Lot of sub events can be reduced.
- [ ] Switch to Z order by the highest, in game properties.
- [ ] With the Update reslution during the game to fit the screen, in game properties, this game is almost ready to use for mobile! Objects on the UI layer have to be reworked a bit, the anchor behavior can be used to pin an object on screen sides.

It's a great example!

**Comment by frolics2dio** [comment]
Thanks for the feedback! I will definitely fix all these issues.

**Comment by frolics2dio** [comment]
## Car Physics Joint Demo



A realistic physics car demo that allows you to enjoy testing a car physics in gdevelop.

## Checklist

**UPDATED**

The car automatically moves when _start engine_ is pressed, is this intentional?
**Answer is yes.**

The README file could be _A fun realistic physics based car example._
**Added.**

- [x] I got stuck on the "Start engine" and "Stop" buttons. These should be gray out or made clear that they are not usable before making a choice between "Keys" or "Touch". 
- [x] Car physics logo on top left corner isn't mandatory
- [x] Lot of sub events can be reduced.
- [x] Switch to Z order by the highest, in game properties.
- [x] With the Update reslution during the game to fit the screen, in game properties, this game is almost ready to use for mobile! Objects on the UI layer have to be reworked a bit, the anchor behavior can be used to pin an object on screen sides.
- [x] A thumbnail.png of 64x64px can be added to the folder, to get a thumbnail in the example list,


## Game folder
[Car Physics Joint Demo.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6912348/Car.Physics.Joint.Demo.zip)

**Comment by Midhil457** [comment]
Hi!,
- The ui still doesn't adapt with the screen. You can easily fix it by using anchor behavior for the ui elements.
![reize](https://user-images.githubusercontent.com/73597906/127774914-6de2ee21-00f5-48fa-8f06-c00609d16672.PNG)

- As bouh mentioned earlier, lot of sub-events can be combined into one. Sub-events might look neat sometimes, but other times a single event is better

- Now the opacity of buttons are set to 50 , is this intentional? if yes, one of the button doesn't get affected 

![opacitywhy](https://user-images.githubusercontent.com/73597906/127775262-c5bb888d-28ca-41a1-8763-7a54d8a04e41.PNG)

![intentional](https://user-images.githubusercontent.com/73597906/127775254-01eda60e-1363-4bb5-87ac-c07729d3b47b.PNG)


- one thing I forgot to mention (😅), the frame `2` and `4` of the animation of the arrow object seems to be same visually, but use separate images, you can use the same image for both (Don't forget to delete the other from the resources and also from the project folder)
![dup](https://user-images.githubusercontent.com/73597906/127775236-fb7d6b78-a19c-4eb2-9f0c-e1afd7cb8929.PNG)

:)

**Comment by frolics2dio** [comment]
Hello,

- Thank you. I did the job of anchoring the buttons earlier but they didn't
work well. So I removed anchor behaviour.

But pedal has anchor behaviour.

For responsive screen I added set position to all ui button elements (At
the beginning of the screen).

But I have to set all objects position to scene window width and check
position for every frame. I think this will work fine.

- I will definitely reduce the extra sub events.

- Yes, I have set button opacity to 50. I didn't want to affect restart
button but I will add this button in that group.

- Animation of the arrow object, I will also fix it up.

Thank you :)

**Comment by frolics2dio** [comment]
## Car Physics Joint Demo



A realistic physics car demo that allows you to enjoy testing a car physics in gdevelop.

## Checklist

**FIXES**

- [x] The ui still doesn't adapt with the screen. You can easily fix it by using anchor behavior for the ui elements. **(Fixed)**
- [x] As bouh mentioned earlier, lot of sub-events can be combined into one. Sub-events might look neat sometimes, but other times a single event is better. **I tried my best to reduce sub events :)**
- [x] Now the opacity of buttons are set to 50 , is this intentional? if yes, one of the button doesn't get affected. **(Fixed)**
- [x] one thing I forgot to mention, the frame 2 and 4 of the animation of the arrow object seems to be same visually, but use separate images, you can use the same image for both (Don't forget to delete the other from the resources and also from the project folder). **(Fixed)**

Thank you :)
## Game folder
[Car Physics Joint Demo.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6915096/Car.Physics.Joint.Demo.zip)

**Comment by Midhil457** [comment]
Hi, I did a quick review again and it looks good. I did add a event to resize the translucent object to the width of the window so that it works fine when resized. Also, changed the example name to Car Physics so that it has the same name as the example it is replacing.
I have made a PR for this and should be added when it gets approved.

Thanks for taking your time and making a great example!

:)

**Comment by 4ian** [comment]
Awesome example! 👍

**Comment by frolics2dio** [comment]
Hi GDevelop,

My pleasure.
Thank you very much for this. Hope this will help those who want to learn
car physics.

Thanks :)

**Comment by Bouh** [comment]
Added to GDevelop, you can use [this direct link ](https://editor.gdevelop-app.com/?project=https://resources.gdevelop-app.com/examples/car-physics/car-physics.json)to try it :)
Thanks for this great game!

Closed by #56
