### ISSUE TITLE
Inventoralia - Inventory and shop

### ISSUE THREAD

**Issue by UlisesFreitas** [GDevelopApp/GDevelop-examples#48]
## An example of inventory and shop all in one with persistent data storage

You can get items by clicking it or buying items in the shop.
To use an item just right click
To delete an item and all its quantity just drag the item to trashcan

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
Here the entire repo: https://github.com/UlisesFreitas/Inventoralia-gdevelop-5-template/tree/1.0.0
Here released project: https://github.com/UlisesFreitas/Inventoralia-gdevelop-5-template/releases/tag/1.0.0
Here the HTML exported: https://github.com/UlisesFreitas/Inventoralia-gdevelop-5-template/blob/main/inventoralia-HTML-1.0.0.zip

Assets are inside the GitHub project
called 
screenshot-1 https://github.com/UlisesFreitas/Inventoralia-gdevelop-5-template/blob/1.0.0/screenshot-1.jpg
screenshot-2 https://github.com/UlisesFreitas/Inventoralia-gdevelop-5-template/blob/1.0.0/screenshot-2.jpg
screenshot-3 https://github.com/UlisesFreitas/Inventoralia-gdevelop-5-template/blob/1.0.0/screenshot-3.jpg

For thumbnail: https://github.com/UlisesFreitas/Inventoralia-gdevelop-5-template/blob/main/icon-512.png
<!--
Finally, attach a zip file containing your game and all its resources (images, sounds, etc...)
Here the entire repo: https://github.com/UlisesFreitas/Inventoralia-gdevelop-5-template/tree/1.0.0
Here released: https://github.com/UlisesFreitas/Inventoralia-gdevelop-5-template/releases/tag/1.0.0

**Comment by Midhil457** [comment]
Hi, great template! This isn't a proper review (The project is large and it might take me a few day to check all the events😅 )

- There are some unused resources, please remove them if not necessary
- Could you make a project with all the screenshots, icons removed? As they are not necessary for the example and is making the project size big and will slow down the opening time when it gets added to the library. Maybe you can keep some of the icons sizes
- Could you organize the folders better, not saying they are not organized, they are organized very well. But, as this is supposed to be a template, people would like to move through and easily find the resources they need. Currently, there seems to be some button assets in sprites instead of hud, etc... Something like, hud, collectables, fonts, music, slots, cursors, etc.. would be fine, sorted according to their use

- You could use a simple panel sprite that can be resized to multiple sizes without losing quality instead of using multiple assets of different sizes

:)

**Comment by UlisesFreitas** [comment]
Ok I will do the changes and re upload

**Comment by UlisesFreitas** [comment]
Updated:
the entire project unfolded events, 
assets moved to Assets/sprites
HUD panels moved to 1 only 9-patch sprite
Screenshots and icon removed

https://github.com/UlisesFreitas/Inventoralia-gdevelop-5-template/releases you must choose 1.0.1 now

Screenshot-1 https://www.ulisesfreitas.com/Inventoralia-gdevelop-5-template/screenshot-1.jpg
Screenshot-2 https://www.ulisesfreitas.com/Inventoralia-gdevelop-5-template/screenshot-2.jpg
Screenshot-3 https://www.ulisesfreitas.com/Inventoralia-gdevelop-5-template/screenshot-3.jpg
Thumbnail: https://www.ulisesfreitas.com/Inventoralia-gdevelop-5-template/icon-512.png

**Comment by Midhil457** [comment]
Hi, great work! I haven't gotten the time to give it a proper look. I will try to make a review this weekend :)

**Comment by Midhil457** [comment]
Hi, I was able to review the events. But, I may have missed some things, so anyone may feel free to review this too

- I don't suggest having a splash screen scene, as it is taking alot of resources, `Wait` and `AutoTyping` extension, etc...
- There are still unused in the folder, go to resources, right click and click `Scan for images` and `Scan for Audio` there are some resource added to the list, meaning that there are some images that are not used in the project folder
- The first animation of the obj_button is invalid

![in_1](https://user-images.githubusercontent.com/73597906/128629179-a0f4fc97-3d3f-4e2d-942a-705ff2a40226.PNG)

- I suggest having the comment color code guide in the Main scene and not in the splash screen
I have added my event review in this copy: 
[Inven.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6950549/Inven.zip)

:)

**Comment by UlisesFreitas** [comment]
Ok, thanks I will make those changes and submit again.
