### ISSUE TITLE
New example - Top Down Action RPG / Action Adventure Camera and Room Transition Example

### ISSUE THREAD

**Issue by Silver-Streak** [GDevelopApp/GDevelop-examples#5]
## Describe the example

This example shows how to accomplish a camera similar to most 2D top down action adventure games (e.g. Zelda). The camera follows the player, within the boundaries of the room they're in, and smoothly moves to the next room once the player moves to another room.

As part of the example I also show how to freeze the player and enemies while the transition is occurring.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [X] My game has all events unfolded.
- [X] I've added myself as the author in the game properties.
- [X] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [X] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I've cleaned unused resources.

## Game folder
[TopDownAdventureCamera.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6608898/TopDownAdventureCamera.zip)

**Comment by arthuro555** [comment]
Very nice and to the point example! I made a slightly altered version:

- Move the "Change the variable CurrentRoom of Character to CameraRoom.Variable(ID)" next to the "Character in collision with CameraRoom" event to make it more clear that object is impacted by object selection
- Use a boolean variable instead of 1 or 0 for the Transition variable 
- Defined the variables to get autocompletions in events.
- Move those events:
  
![image](https://user-images.githubusercontent.com/19349038/121027219-14f50580-c7a7-11eb-820f-8e3f3bc84bdc.png)

inside the "Room Transition Logic" group as they aren't camera logic but transition logic.

Here is the modified file: [TopDownAdventureCamera.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6609523/TopDownAdventureCamera.zip)

### Some other notes I have made while looking at the game:

![image](https://user-images.githubusercontent.com/19349038/121027888-9cdb0f80-c7a7-11eb-8b78-d88b663aa5c5.png)

- Why are the values rounded here? Wouldn't that make the transition end a bit early? Is it intended to end a bit early? If so, why?
- Should the variable "Transition" be renamed to "Transitioning"?
- Should the YSort extension be used on the character + miners? Would that be bloating the example?
- Should the assets be more organized (`CameraRoom-1-1.png` -> `CameraRoom.png`, move the assets to an assets folder...)?

**Comment by Silver-Streak** [comment]
> * Why are the values rounded here? Wouldn't that make the transition end a bit early? Is it intended to end a bit early? If so, why?

I found that without rounding them and the camera being float, the camera was never detected as being = to the variable. As we currently cannot use the project-wide Round Pixels setting, I rounded the variables.

> * Should the variable "Transition" be renamed to "Transitioning"?
The variable could be named anything, for the purposes of this example just think of it as "Is it in a transition state".

> * Should the YSort extension be used on the character + miners? Would that be bloating the example?
I think that would bloat this example a bit. It's not intended to be a full Top Down adventure game example, just a method of showing how the camera and room transitions could work.

> * Should the assets be more organized (`CameraRoom-1-1.png` -> `CameraRoom.png`, move the assets to an assets folder...)?
Piskel automatically adds the -1 to created images, and decided to rename it to -1-1 when I resized it.

Until we actually some sort of automatic asset management in the engine, I wouldn't want to treat the example's folder structure any different than anyone else.

**Comment by arthuro555** [comment]
I don't know if there is any protocol in place for reviewing and adding examples, but in the case that it matters, I am officially approving this example.

**Comment by Silver-Streak** [comment]
Pinging @4ian as we probably need an official process listed on how these are handled, especially for the moderator/approvers sake.

**Comment by 4ian** [comment]
That's a good question, not sure what the exact process should be? Probably something fairly simple, we can wait for at least a review of a regular community member checking for the quality of the example (and asking about any changes like you did here), then when it's approved by this community member or someone else, we go ahead (either you tag me like this or open a PR).
I won't review everything in all their details, just keeping an eye on the examples. If things are going well, we could also have people having the merge rights that could go ahead without my blessing.

In the case of this example, I just pushed it :) It should be online after a few minutes (the time for the automatic build and deploy to be done) (also, note that in the case of an example update, there will be additional time because of the "caching" done by Cloudflare.)

**Comment by 4ian** [comment]
Closing as added 👍
